# Generated by Django 5.0.2 on 2024-04-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статья'},
        ),
    ]
