# Generated by Django 5.0.2 on 2024-04-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_article_deleted_at_article_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активна'), ('NOT_ACTIVE', 'Неактивна')], default='ACTIVE', max_length=20, verbose_name='Статус'),
        ),
    ]
